### ISSUE TITLE
Sign Up Errors Do Not Stack Upon Display

### ISSUE THREAD

**Issue by Khaled-Ayman1** [MHani0/Vaccine-Tracking-System#3]
Purposely messing up the sign up on multiple fields wouldn't show all the errors at the same time, here's an example:

On leaving Full Name and ID blank, only output is:

> Name is a Required Field

and upon resolving and resubmitting it starts to sequentially traverse through the error fields.

> ID should be 14 characters
..
..

### Solution:

A possible solution would be reconstructing the validation logic, as it's time optimized at the cost of this bug, a crooky if that validates all conditions at once might resolve the issue

### - Old Code:

```c++

if(constraint 1)
    do;
    return;
if(constraint 2)
    do;
    return;
if(constraint 3)
    do;
    return;
else
    validate;
```

### - Proposed Solution (Optimized)

```c++
int counter =  0;
if(constraint 1)
    do;
    counter++;
if(constraint 2)
    do;
    counter++;
if(constraint 3)
    do;
    counter++;
if(counter == 3)   //instead of revalidating the whole block in a single statement
    validate;
```

**Comment by MHani0** [comment]
Fixed by binding an event to each text box, once focus is lost, the validation is triggered instead of triggering it when sign up button clicked
